### ISSUE TITLE
Game stat swag

### ISSUE THREAD

**Issue by larongbingo** [BernabePosadas/OkuhanaHanako#12]
Allow discord users to flex their game profiles
Suggested Integrations for swag
- Steam
- Osu

Yeah that's it, those are the most popular
Suggested commands would be
;swag steam setup <user_id> // stores the id 
;swag steam // flex on them fools

This is unnecessary and has no future proofing and no value other than flexing.

**Comment by BernabePosadas** [comment]
best bet is steam as they have api for viewing user info

**Comment by BernabePosadas** [comment]
Steam API requires me to spend 5$ for API use kek.
