### ISSUE TITLE
LaunchCodes source

### ISSUE THREAD

**Issue by larongbingo** [BernabePosadas/OkuhanaHanako#38]
Allow other H source/websites to post.

Ex,
!launchnuke nh 000000 - should post from nhentai
!launchnuke hn 000000 - should post from hentai nexus

but by default we should use nhentai
!launchnuke 000000 111111 - should post 2 H from nhentai

**Comment by BernabePosadas** [comment]
hnexus has an API to fetch doujin info tho?

**Comment by larongbingo** [comment]
haha dont know xd

**Comment by BernabePosadas** [comment]
XD researching there is none

**Comment by BernabePosadas** [comment]
it will be sad for posting as it will only reply back a link 


unless i web scrape it
